// <auto-generated />
using System;
using API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230220043728_new_migration")]
    partial class new_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Pelanggan", b =>
                {
                    b.Property<string>("NoidentitasKTP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlamatKTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlamatPerusahaan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JenisKelamin")
                        .HasColumnType("int");

                    b.Property<string>("JumlahKredit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kecamatan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kelurahan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KodeAgama")
                        .HasColumnType("int");

                    b.Property<string>("KodeGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeLokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeNamaPanggilan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodePos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kodeposrumah")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NPPSales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NPWP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NPWPPerusahaan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaBelakang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaBelakangPasangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaDepan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaDepanPasangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaIbuKandung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPerusahaan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoHP")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoIdentitasPasangan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Pekerjaan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PendapatanPerbulan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusPerkawinan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TanggalLahir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TanggalLahirPasangan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TanggalLahirPemegangSaham")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TanggalPendirianPerusahaan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeleponKantor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TempatLahir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TujuanPenggunaan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NoidentitasKTP");

                    b.HasAlternateKey("NoHP");

                    b.HasAlternateKey("NoIdentitasPasangan");

                    b.ToTable("APP_CHANNEL_TEMP");
                });
#pragma warning restore 612, 618
        }
    }
}
